In [2]:
import csv

with open("C:\\Users\\aimor\\Desktop\\students.csv", "r") as f:
    reader = csv.reader(f)
    next(reader)  #skip header
    for row in reader:
        name = row[0]
        grade = int(row[1])

        if grade >= 50:
            print(f"{name} Passed")
        else:
            print(f"{name} Failed")

Steven Passed
Neena Passed
Lex Passed
Alex Passed
Olive Passed
David Failed


In [4]:
total = 0
with open("C:\\Users\\aimor\\Desktop\\product.csv", "r") as f:
    reader = csv.reader(f)
    next(reader)  #skip header
    for row in reader:
        total += float(row[1])

print("Total sales :", total)

Total sales : 115.0


In [7]:
import numpy as np

arr = [1,2,3,4,5]
print(arr)

arr = np.array([1,2,3,4,5])
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
#3D array: Array of arrays of arrays.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
print(arr.shape)
print(arr.size)

(2, 2, 2)
8


In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [14]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [17]:
#                0 1 2  0 1  2   0  1 2
#                  0        1      2
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:3, 0:2])

[[1 2]
 [4 5]
 [7 8]]


In [22]:
#                0   1   0   1     0   1   0   1
#                  0       1        0        1
#                       0                 1
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[0:2, 0:1, 0:2])

[[[1 2]]

 [[5 6]]]


In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2  
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [24]:
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  
print(np.mean(arr))

10
2.5


In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [26]:
#Common NumPy Functions:
print(np.array([1, 2, 3]) )
print(np.zeros((2, 3)))
print(np.ones((2, 2)))
print(np.arange(0, 10, 2))   
print(np.linspace(1, 5, 4))

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[1.         2.33333333 3.66666667 5.        ]


In [27]:
arr = np.array([1, 2,4, 5, 6,7,8,9,10])
reshaped = arr.reshape(3, 3)
print(reshaped)

[[ 1  2  4]
 [ 5  6  7]
 [ 8  9 10]]
